[tox]
envlist = py{312,313}, lint, type
skip_missing_interpreters = true
isolated_build = true
labels =
    test = py312, py313
    qa = lint, type

[testenv]
allowlist_externals = uv
commands_pre =
    uv sync --group dev
commands =
    uv run pytest -v --tb=short --cov=src/django_scotty --cov-report=term-missing

[testenv:lint]
commands =
    uv run ruff check src/django_scotty tests
    uv run ruff format --check src/django_scotty tests

[testenv:type]
commands =
    uv run mypy src/django_scotty
